name: "CodeQL"

on: [push, pull_request]

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: pip install jupytext
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: find . -maxdepth 10 -name \*.ipynb -exec jupytext --to py:percent {} \;
    - name: Copy leakage.ql from public repository
      run: |
        curl -o ${{ github.workspace }}/over_sampling.ql https://raw.githubusercontent.com/harel-coffee/codeql-ml/main/over_sampling.ql
        curl -o ${{ github.workspace }}/feature_selection.ql https://raw.githubusercontent.com/harel-coffee/codeql-ml/main/feature_selection.ql
        curl -o ${{ github.workspace }}/qlpack.yml https://raw.githubusercontent.com/harel-coffee/codeql-ml/main/qlpack.yml

    - name: Download CodeQL CLI 2.13.5
      run: |
        curl -L -o codeql.zip https://github.com/github/codeql-cli-binaries/releases/download/v2.13.5/codeql-linux64.zip
        unzip codeql.zip -d /opt/hostedtoolcache/CodeQL/2.13.5
        sudo ln -sf /opt/hostedtoolcache/CodeQL/2.13.5/codeql/codeql /usr/bin/codeql

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2.13.5
      with:
        languages: ${{ matrix.language }}
        queries: ./over_sampling.ql,./feature_selection.ql

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2.13.5
      with:
        category: "/language:${{matrix.language}}"
