name: "CodeQL"

on: [push, pull_request]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download CodeQL CLI
      run: |
        curl -L -o codeql-linux64.zip https://github.com/github/codeql-cli-binaries/releases/download/v2.15.5/codeql-linux64.zip
        unzip codeql-linux64.zip -d codeql

    - name: Set up CodeQL CLI
      run: |
        sudo cp -r codeql/* /usr/local/

    - name: Initialize CodeQL
      run: |
        /usr/local/codeql/codeql init --languages=${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      run: |
        /usr/local/codeql/codeql analyze --category="/language:${{ matrix.language }}" ./over_sampling.ql ./feature_selection.ql
